export enum sortType {
  CREATE_TIME_ASC,
  CREATE_TIME_DESC,
  UPDATE_TIME_ASC,
  UPDATE_TIME_DESC,
  FOLLOW_COUNT_ASC,
  FOLLOW_COUNT_DESC,
  VIEW_COUNT_ASC,
  VIEW_COUNT_DESC,
  THUMB_UP_COUNT_ASC,
  THUMB_UP_COUNT_DESC,
  THUMB_DOWN_COUNT_ASC,
  THUMB_DOWN_COUNT_DESC
}
